require 'shelljs/global'


exec 'npm link bower'
exec 'npm link less'
exec 'npm link coffee-script'
exec 'npm link to'
exec 'npm install graceful-fs'
exec 'npm install js-yaml'
exec 'npm install minimatch'
exec 'npm install lodash'
exec 'npm install globule'
exec 'npm install glob'
exec 'npm install async'
exec 'npm install underscore.string'
exec 'npm install ent'
exec 'npm install matchdep'
exec 'npm install slug'
exec 'npm install js-beautify'
exec 'npm install moment'
exec 'npm install fs-utils'
exec 'npm install assemble-yaml'
exec 'npm install gray-matter'
exec 'npm install highlight.js'
exec 'npm install marked'
exec 'npm install yfm2json'
exec 'npm install html-minifier'
exec 'npm install lorem-ipsum'
exec 'npm install'

exec 'bower install'
exec 'grunt bowercopy'
exec 'grunt initialize'
